Nomination page for epic's
FuelRats/fuelrats.com pull request #316
Opened 2021-04-12 18:08 UTC by Delota

Files added:

- **RescueIdFieldset** Field for validation of correct UUID
- **EpicNominationForm** Wrapper that holds the `RescueNominationForm` and the `RatNominationForm`(coming later)
-  **NominateRescueForm.js** Holds the form and logic for calling the `searchRescueApi` and `createEpicApi`
- **RescueDetail.js** Is loaded with rescue data when a rescue is found
- **useSearchRescueApi/useCreateEpicApi.js** Wrappers for redux calls. Make sure that the Forms are not dealing with API directly4

Todo before merging:
- [ ] Change regex to UUIDv4 validation
- [ ] Create link to this page
- [ ] Make sure FuelRatsApi has epic.write on regular rats

To come after this PR in no particular order:
- Page to nominate without a rescue(single rat)
- Page for managing the epics
- Page for redeeming your epic

Impression:

![form3](https://user-images.githubusercontent.com/79107184/114440776-d25de500-9bca-11eb-9aa9-a90c03bf9289.gif)

2021-04-12 20:05 UTC, kenneaal commented
Looks good, stylelint errors should probably be fixed before PR is finalized. Is epic.write permission for regular rats the blocker at this point? @xlexi , do we perhaps need to break out a more granular permission set for this, so rats can nominate, but not otherwise change epic data?

2021-04-12 20:19 UTC, xlexi commented
I plan to sort this issue with just an exception in the add endpoint requiring no additional permission to set these fields on creation, however I will be unable to make these changes until later this week.

2021-04-15 19:20 UTC, UncleClapton requested changes
Overall great stuff! I got both a few notes and stuff that needs fixing/talking about.

2021-04-15 19:20 UTC, UncleClapton commented on src/components/Fieldsets/RescueIdFieldset.js
> +      if (!isValidUuidV4(value)) {
Making a note of it here so I don't forget to make a ticket on this, but eventually we should check the validity of the rescue ID against the API. The validation callbacks can be asynchronous. 

Lets keep it as-is for this PR though

2021-04-15 19:20 UTC, UncleClapton commented on src/components/Fieldsets/RescueIdFieldset.js
> +      type="text"
Type is implicitly text with `<InputFieldset />` so this is redundant

2021-04-15 19:20 UTC, UncleClapton commented on src/pages/epic/nominate.js
> +export default class EpicNominatePage extends React.Component {
with how simple this file is now, this could be turned into a function component as well.

For the page meta, it can be tagged onto the function object like traditional "static" members of function-style classes

```jsx
EpicNominatePage.getPageMeta = () => {/*...*/}
```

2021-04-15 19:20 UTC, UncleClapton commented on src/hooks/frapi/useSearchRescueApi.js
> +export default function useSearchRescueApi (initialRescueId = null) {
I'm accepting this and the other hook for now, but this should be made generic in the future. I'm already seeing redundancies between this and the other one that could be smoothed out.

2021-04-15 19:20 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/EpicNominationForm.js
> +      {type === 'RAT' && <p> {'Coming soon...'}</p>}
coming soon? 🤣

2021-04-15 19:20 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/EpicNominationForm.js
> +type === 'RESCUE'
The spacing here got a bit screwed up, I think 😆.

Unfortunately the linter doesn't take formatting expression blocks in JSX too well, so the first line needs to be intended 2 spaces from the opening bracket to properly format.

2021-04-15 19:20 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/RescueDetail.js
> +export default function RescueDetail (props) {
I'm not sure how to feel about adding yet another view for rescue information, and further I don't think all of the details are necessary. there's a couple options I guess.

1. there's a card-like layout in `pages/admin/rescues` that could be reused.
1. We make that new rescue card design for the dispatch board I've been toying with a real thing, and reuse it here.
1. leave it as is for now and wait til dispatch board stuff is finalized, and swap it out then.

2021-04-15 19:20 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/RescueDetail.js
> +rats.map((rat) => {
indentation

2021-04-15 19:20 UTC, UncleClapton commented on src/hooks/frapi/useSearchRescueApi.js
> +  const rescueFetchReducer = (state, action) => {
This reducer could be defined outside of the function just so it doesn't have to get defined every call.

2021-04-15 19:22 UTC, UncleClapton requested changes

2021-04-15 19:22 UTC, UncleClapton commented on src/hooks/frapi/useCreateEpicApi.js
> +  const rescueFetchReducer = (state, action) => {
Just like the other hook, this could be defined outside the hook.

2021-04-15 19:26 UTC, Delota commented on src/hooks/frapi/useSearchRescueApi.js
> +export default function useSearchRescueApi (initialRescueId = null) {
Yes there are many redundancies, I agree, a more generic one is good. I'm sure I'll bump into it on the next pages

2021-04-15 19:33 UTC, Delota commented on src/components/Forms/EpicNominationForm/RescueDetail.js
> +export default function RescueDetail (props) {
Short-term I'd go for 3. Mid-to Long term definitely 2!
Not sure how to re-use the block in `pages/admin/rescues` as is.

2021-04-15 19:37 UTC, Delota commented on src/components/Fieldsets/RescueIdFieldset.js
> +      if (!isValidUuidV4(value)) {
Yes, right now it's just doing the pure format validation, in the future, we can include it into the RescueIdFielset where it does an actual check.
Right now the Epic Form does a check anyway

2021-04-15 19:40 UTC, Delota commented on src/components/Forms/EpicNominationForm/EpicNominationForm.js
> +      {type === 'RAT' && <p> {'Coming soon...'}</p>}
Yes, that's going to be the other form, which does require different handling, but the radiofieldset was there already 😆

2021-04-15 19:52 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/RescueDetail.js
> +export default function RescueDetail (props) {
well I still feel like I could use a bit more feedback from the mischief before I really push for any sort of final design of the rescue card. 3 probably best.

2021-04-15 20:29 UTC, UncleClapton requested changes

2021-04-15 20:29 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/EpicNominationForm.js
> +      {type === 'RAT' && <p> {'Coming soon...'}</p>}
Is there anything blocking that from being completed this PR?

2021-04-16 22:20 UTC, Delota commented
@UncleClapton 
> Is there anything blocking that from being completed this PR?

This has now been added!

2021-04-18 20:35 UTC, UncleClapton requested changes

2021-04-18 20:35 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/NominateRatForm.js
> +      </fieldset>
This is a good stopgap for now but it's certainly giving us more of a reason to rewrite `<TagsInput />`.

WE SHOULD MAKE @trezy DO IT! 😏

2021-04-18 20:35 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/NominateRatForm.js
> +      <InputFieldset required id="notes" label="What did the rat do that makes him so epic?" name="attributes.notes" />
```suggestion
      <InputFieldset required id="notes" label="What did the rat do that makes them so epic?" name="attributes.notes" />
```

Please prefer gender neutral pronouns 😄

2021-04-18 20:35 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/EpicNominationForm.js
> +      </Form>
I'm just now realizing what you're doing here.

`<RadioFieldset />` uses `<RadioInput />` internally. I'd recommend just using that on it's own here instead of spinning up an entire `useForm()` instance.

There's a few input components that require an `useForm()` instance to function properly, but in this case the fieldset is just an adaption layer for an existing generic input component.

I'm going to start documentation on forms and fields, and in that I'll make the separation of Input and `useForm()` fieldset a requirement moving forward to avoid this.

2021-04-18 20:35 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/NominateRatForm.js
> +/* eslint-disable react/jsx-no-bind */
This isn't an eslint rule to be ignored. 
Please consult me for a solution before ignoring rules like this.

Callbacks defined in function scope which are used in JSX or passed to other hooks should be wrapped with the `useCallback()` hook so they are provided with a stable function instance.

2021-04-18 20:35 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/EpicNominationForm.js
> +/* eslint-disable react/jsx-no-bind */
See `NominateRatForm.js` comment

2021-04-18 20:35 UTC, UncleClapton commented on src/components/Forms/EpicNominationForm/NominateRescueForm.js
> +/* eslint-disable react/jsx-no-bind */
See `NominateRatForm.js` comment

2021-04-18 20:55 UTC, UncleClapton approved these changes
LGTM!

2021-04-18 20:58 UTC, UncleClapton commented
@all-contributors please add @Delota for code

2021-04-18 20:58 UTC, merged