Feature/change email
FuelRats/fuelrats.com pull request #407
Opened 2024-11-04 14:09 UTC by evertiro

## Changelog
Adds an option to user profiles to change their registered email address.

### ✨ Additions
* Added Change E-Mail button and associated modal to user profiles

## Contributor's Checklist

- [ ] This PR was created to resolve an existing issue or set of issues.
- [ ] This PR satisfies any and all acceptance criteria laid out by issue(s) it resolves.
- [ ] I have discussed creating this PR with the maintainers in the issue(s) beforehand.
- [x] I have thoroughly tested the changes this PR introduces in a local development environment.
- [x] I have linted the entire codebase using `yarn lint` and confirmed there are no errors or warnings.
- [x] I have followed the commit conventions laid out by [`CONTRIBUTING.md`](https://github.com/FuelRats/fuelrats.com/blob/develop/CONTRIBUTING.md#commit-conventions).

## Maintainer's Checklist

- [ ] User-facing changes this PR introduces has been or will be documented in `CHANGELOG.md`.
- [ ] This PR has been linted and tested locally as a part of the review process.
- [ ] All issues this PR resolves have been properly linked before merging.

2024-11-04 21:34 UTC, UncleClapton requested changes
This looks great! just a couple things to clean up :)

2024-11-04 21:34 UTC, UncleClapton commented on src/store/actionTypes.js
> +}
lets move this so it's a sub-group of the `user` actions named `email`, since it only pertains to the user's email.

2024-11-04 21:34 UTC, UncleClapton commented on src/store/actions/authentication.js
> +
Lets move this to the `user` actions file.

2024-11-04 23:14 UTC, evertiro commented on src/store/actions/authentication.js
> +
Resolved with 5a97cf5d7f37f26d283b29bd0b4c7b5d810b24ba

2024-11-04 23:14 UTC, evertiro commented on src/store/actionTypes.js
> +}
Resolved with 5a97cf5d7f37f26d283b29bd0b4c7b5d810b24ba

2024-11-05 01:42 UTC, UncleClapton approved these changes
LGTM 🎉

2024-11-05 01:42 UTC, UncleClapton approved these changes

2024-11-05 01:43 UTC, merged